---
language: python
services: docker

env:
  global:
    - ROLE_NAME: zsh
  matrix:
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd

install:
  # Install test dependencies
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory
  - cd ../
  - mv ansible-role-$ROLE_NAME tocyuki.$ROLE_NAME
  - cd tocyuki.$ROLE_NAME

script:
  # Run tests
  - molecule test
