---
# tasks file for ansible-role-zsh
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install golang
  yum:
    name: golang
    state: latest

- name: Install zsh
  yum:
    name: zsh
    state: latest

- name: Clone zplug
  git:
    repo: "{{ zplug_repo }}"
    dest: $HOME/.zplug
    version: master

- name: Install ghq
  command: go get github.com/motemen/ghq
