---
# tasks file for ansible-role-zsh
- name: Install libralies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - zsh
    - ghq

- name: Clone zplug
  git:
    repo: "{{ zplug_repo }}"
    dest: $HOME/.zplug
    version: master

- name: Install ghq
  command: go get github.com/motemen/ghq
