---
# tasks file for ansible-role-zsh
- name: Install libraries
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - zsh
    - golang

- name: Clone zplug
  git:
    repo: "{{ zplug_repo }}"
    dest: $HOME/.zplug
    version: master

- name: Install ghq
  command: go get github.com/motemen/ghq

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    dest: $HOME/dotfiles
    version: master

- name: Create link
  file:
    src: "$HOME/dotfiles/{{ item }}"
    dest: "$HOME/{{ item }}"
    state: link
  with_items:
    - .zshenv
    - .zshrc
